# Generated by Django 3.0.7 on 2020-06-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200605_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics_week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=100)),
                ('data', models.FloatField(default=0)),
            ],
        ),
    ]
